---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: comet
  namespace: argocd
spec:
  description: "Comet Project"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'