apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-repo-sshkey-external-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argo-repo-sshkey-secret-store
    kind: ClusterSecretStore
  target:
    name: argo-repo-ssh-key
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      # Use inline templates to construct your desired config file that contains your secret
      data:
        type: git
        url: git@gitlab.com:comet-rocks/infra/argocd.git
        sshPrivateKey: |
          {{ .sshPrivateKey | toString }}
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: repo-ssh-key
      property: private