apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: argo-repo-sshkey-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
