arbiter:
    enabled: true
architecture: replicaset
replicaCount: 3
replicaSetName: rs0

persistence:
  size: 5Gi

# Use the initContainer to change permissions for us so Mongo can write to the volume
volumePermissions.enabled: true

auth:
  enabled: true
  rootUser: root
  existingSecret: "mongodb-secrets"

# service:
# externalAccess:
#   enabled: true
#   type: NodePort
#   ports:
#     mongodb: 27017