apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-comet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: comet
  source:
    repoURL: https://github.com/ajitsingh25/argocd-catalog.git
    targetRevision: HEAD
    path: argocd-apps/micro-apps/templates/
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true