apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comet
  namespace: argocd
spec:
  project: comet
  source:
    repoURL: git@github.com:ajitsingh25/argocd-catalog.git
    targetRevision: HEAD
    path: argocd-apps/micro-apps
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false