---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-devops
  namespace: argocd
spec:
  project: devops
  source: 
    repoURL: git@gitlab.com:comet-rocks/infra/argocd.git
    targetRevision: HEAD
    path: argocd-apps/devops/charts
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true