---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-devops
  namespace: argocd
spec:
  project: devops
  source: 
    repoURL: https://github.com/ajitsingh25/argocd-catalog.git
    targetRevision: HEAD
    path: argocd-apps/devops
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true