apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongodb
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongodb-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-mongodb-headless

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-srv
  namespace: mongodb
spec:
  selector:
    app: mongo-express
#   type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP