apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-external-secrets
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: mongodb-secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb-secrets
    creationPolicy: Owner
  data:
  - secretKey: mongodb-root-password
    remoteRef:
      key: stage-mongodb-password #asm secret key 
      property: password #asm secret