apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: comet
  source:
    repoURL: https://github.com/ajitsingh25/argocd-catalog.git
    targetRevision: HEAD
    path: argocd-apps/micro-apps/charts
  destination:
    server: https://F31BA20E6104629F7038CDFC685371C6.gr7.eu-central-1.eks.amazonaws.com
    name: stage-comet-eu-central-1
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false